FROM postgres:15-bullseye

RUN apt-get update \
    && apt-get install -y postgresql-15-postgis-3 \
    && apt-get install -y postgresql-15-postgis-3-scripts \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /docker-entrypoint-initdb.d
COPY ./init-postgis.sql /docker-entrypoint-initdb.d/10-init-postgis.sql