version: '3.9'

services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: bash -c " 
  #     cd src &&
  #     uvicorn main:app
  #     --host 0.0.0.0 --port 8989
  #     --reload"       
  #   volumes:
  #     - backend_volume:/opt
  #   ports:
  #     - "8989:8989"
  #   depends_on:
  #     - postgres
  #     - redis

  postgres:
    container_name: postgres_container
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    restart: unless-stopped
  redis:
    image: redis:7.4.1-alpine
    container_name: redis
    ports:
      - "6380:6379"
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    volumes:
      - redis_data:/data
    restart: unless-stopped
    
    

      
volumes:
  # backend_volume:
  postgres_data:
  redis_data: